name: Trigger auto deployment for container-app-pv3fw2lurl7h2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-pv3fw2lurl7h2-AutoDeployTrigger-4865ddbf-7868-48b9-8412-7f7b54f54c0b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPPV3FW2LURL7H2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPPV3FW2LURL7H2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPPV3FW2LURL7H2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: defaultacrcontainerregistry8e0b.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPPV3FW2LURL7H2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPPV3FW2LURL7H2_REGISTRY_PASSWORD }}
          containerAppName: container-app-pv3fw2lurl7h2
          resourceGroup: reactbasica15bb86b
          imageToBuild: defaultacrcontainerregistry8e0b.azurecr.io/container-app-pv3fw2lurl7h2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


